config:
  info: master branch,springcloud-config/application-dev.yml version=7.0


server:
  port: 3355

spring:
  #rabbit相关配置 15672是web管理界面的端口，5672是MQ访问的端口
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

#服务注册到eureka地址
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8088/eureka

#暴露监控端点
management:
  endpoints:
    web:
      exposure:
        include: "*"
 
